###########################################################################
# Copyright 2024 Broadband Forum
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###########################################################################
version: '3.5'
networks:
    obcas_e2e:
        driver: bridge
        name: obcas_e2e
        ipam:
          driver: default
          config:
            - subnet: 172.47.0.0/16

services:
    zookeeper:
      image: confluentinc/cp-zookeeper:5.5.0
      hostname: zookeeper
      container_name: zookeeper
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000
      networks:
        obcas_e2e:
          ipv4_address: 172.47.0.2

    kafka:
      image: confluentinc/cp-kafka:5.5.0
      hostname: kafka
      container_name: kafka
      depends_on:
        - zookeeper
      ports:
        - "29092:29092"
        - "9092:9092"
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      networks:
        obcas_e2e:
          ipv4_address: 172.47.0.3

    vomci:
      image: broadbandforum/obbaa-vomci:develop
      hostname: obbaa-vomci
      container_name: obbaa-vomci
      ports:
        - 8801:8801
        - 58433:58433
      environment:
        GRPC_SERVER_NAME: vOMCi-grpc-1
        LOCAL_GRPC_SERVER_PORT: 58433
        # Kafka bootstrap server, please provide only one address
        KAFKA_BOOTSTRAP_SERVER: "kafka:9092"
        # List of Consumer topics, seperated by spaces
        KAFKA_REQUEST_TOPICS: "vomci1-request" # if message formatter is JSON "OBBAA_ONU_REQUEST"
        KAFKA_RESPONSE_TOPICS: 'vomci1-response' # if message formatter is JSON 'OBBAA_ONU_RESPONSE'
        KAFKA_NOTIFICATION_TOPICS: "vomci1-notification" # if message formatter is Json "OBBAA_ONU_NOTIFICATION"
        KAFKA_TELEMETRY_TOPICS: "vomci1-telemetry"
        VOMCI_KAFKA_SENDER_NAME: "bbf-vomci"
        VOMCI_KAFKA_VOLTMF_NAME: "vOLTMF"
      networks:
        obcas_e2e:
          ipv4_address: 172.47.0.4
      volumes:
        - /baa/stores/vomci-function-db:/db
      depends_on:
        - zookeeper
        - kafka

    vproxy:
      image: broadbandforum/obbaa-vproxy:develop
      hostname: obbaa-vproxy
      container_name: obbaa-vproxy
      ports:
        - 8433:8433
      environment:
        GRPC_CLIENT_NAME: proxy-grpc-1
        GRPC_SERVER_NAME: proxy-grpc-2
        LOCAL_GRPC_SERVER_PORT: 8433
        REMOTE_GRPC_SERVER_PORT: 58433
        REMOTE_GRPC_SERVER_ADDR: obbaa-vomci
        KAFKA_BOOTSTRAP_SERVER: "kafka:9092"
        # List of Consumer topics, seperated by spaces
        KAFKA_REQUEST_TOPICS: "vomci-proxy-request"
        KAFKA_RESPONSE_TOPICS: 'vomci-proxy-response'
        KAFKA_NOTIFICATION_TOPICS: "vomci-proxy-notification"
        VOMCI_KAFKA_SENDER_NAME: "bbf-vproxy"
        VOMCI_KAFKA_VOLTMF_NAME: "vOLTMF"
      networks:
        obcas_e2e:
          ipv4_address: 172.47.0.5
      volumes:
        - /baa/stores/vomci-vproxy-db:/db
      depends_on:
        - vomci

    polt-simulator1:
      image: broadbandforum/obbaa-polt-simulator:develop
      stdin_open: true
      tty: true
      container_name: polt-simulator1
      #command: ["-dummy_tr385","-f","/certificates/cli_scripts_new/read_certs_start_server_new.cli"]
      command: ["-dummy_tr385"]
      hostname: polt-simulator1
      environment:
        - PASSWD=root
        - POLT_SIMULATOR_REST_API_PORT=3002
      ports:
        - "10830:10830"
        - "3002:3002"
      #volumes:
        #- ./cli_scripts_new:/certificates/cli_scripts_new
      networks:
        obcas_e2e:
          ipv4_address: 172.47.0.6

    polt-simulator2:
      image: broadbandforum/obbaa-polt-simulator:develop
      stdin_open: true
      tty: true
      container_name: polt-simulator2
      #command: ["-dummy_tr385","-f","/certificates/cli_scripts_new/read_certs_start_server_new.cli"]
      command: ["-dummy_tr385"]
      hostname: polt-simulator3
      environment:
        - PASSWD=root
        - POLT_SIMULATOR_REST_API_PORT=3003
      ports:
        - "10831:10830"
        - "3003:3003"
      #volumes:
       # - ./cli_scripts_new:/certificates/cli_scripts_new
      networks:
        obcas_e2e:
          ipv4_address: 172.47.0.7

    polt-simulator3:
      image: broadbandforum/obbaa-polt-simulator:develop
      stdin_open: true
      tty: true
      container_name: polt-simulator3
      #command: ["-dummy_tr385","-f","/certificates/cli_scripts_new/read_certs_start_server_new.cli"]
      command: ["-dummy_tr385"]
      hostname: polt-simulator3
      environment:
        - PASSWD=root
        - POLT_SIMULATOR_REST_API_PORT=3004
      ports:
        - "10832:10830"
        - "3004:3004"
      #volumes:
       # - ./cli_scripts_new:/certificates/cli_scripts_new
      networks:
        obcas_e2e:
          ipv4_address: 172.47.0.8

    polt-simulator4:
      image: broadbandforum/obbaa-polt-simulator:develop
      stdin_open: true
      tty: true
      container_name: polt-simulator4
      #command: ["-dummy_tr385","-f","/certificates/cli_scripts_new/read_certs_start_server_new.cli"]
      command: ["-dummy_tr385"]
      hostname: polt-simulator4
      environment:
        - PASSWD=root
        - POLT_SIMULATOR_REST_API_PORT=3005
      ports:
        - "10833:10830"
        - "3005:3005"
      #volumes:
        #- ./cli_scripts_new:/certificates/cli_scripts_new
      networks:
        obcas_e2e:
          ipv4_address: 172.47.0.9

    polt-simulator5:
      image: broadbandforum/obbaa-polt-simulator:develop
      stdin_open: true
      tty: true
      container_name: polt-simulator5
      #command: ["-dummy_tr385","-f","/certificates/cli_scripts_new/read_certs_start_server_new.cli"]
      command: ["-dummy_tr385"]
      hostname: polt-simulator5
      environment:
        - PASSWD=root
        - POLT_SIMULATOR_REST_API_PORT=3006
      ports:
        - "10834:10830"
        - "3006:3006"
      #volumes:
       # - ./cli_scripts_new:/certificates/cli_scripts_new
      networks:
        obcas_e2e:
          ipv4_address: 172.47.0.10

    polt-simulator6:
      image: broadbandforum/obbaa-polt-simulator:develop
      stdin_open: true
      tty: true
      container_name: polt-simulator6
      #command: ["-dummy_tr385","-f","/certificates/cli_scripts_new/read_certs_start_server_new.cli"]
      command: ["-dummy_tr385"]
      hostname: polt-simulator6
      environment:
        - PASSWD=root
        - POLT_SIMULATOR_REST_API_PORT=3007
      ports:
        - "10835:10830"
        - "3007:3007"
      #volumes:
        #- ./cli_scripts_new:/certificates/cli_scripts_new
      networks:
        obcas_e2e:
          ipv4_address: 172.47.0.11

    polt-simulator7:
      image: broadbandforum/obbaa-polt-simulator:develop
      stdin_open: true
      tty: true
      container_name: polt-simulator7
      #command: ["-dummy_tr385","-f","/certificates/cli_scripts_new/read_certs_start_server_new.cli"]
      command: ["-dummy_tr385"]
      hostname: polt-simulator7
      environment:
        - PASSWD=root
        - POLT_SIMULATOR_REST_API_PORT=3008
      ports:
        - "10836:10830"
        - "3008:3008"
      #volumes:
        #- ./cli_scripts_new:/certificates/cli_scripts_new
      networks:
        obcas_e2e:
          ipv4_address: 172.47.0.12

    polt-simulator8:
      image: broadbandforum/obbaa-polt-simulator:develop
      stdin_open: true
      tty: true
      container_name: polt-simulator8
      #command: ["-dummy_tr385","-f","/certificates/cli_scripts_new/read_certs_start_server_new.cli"]
      command: ["-dummy_tr385"]
      hostname: polt-simulator8
      environment:
        - PASSWD=root
        - POLT_SIMULATOR_REST_API_PORT=3009
      ports:
        - "10837:10830"
        - "3009:3009"
      #volumes:
       # - ./cli_scripts_new:/certificates/cli_scripts_new
      networks:
        obcas_e2e:
          ipv4_address: 172.47.0.13

    polt-simulator9:
      image: broadbandforum/obbaa-polt-simulator:develop
      stdin_open: true
      tty: true
      container_name: polt-simulator9
      #command: ["-dummy_tr385","-f","/certificates/cli_scripts_new/read_certs_start_server_new.cli"]
      command: ["-dummy_tr385"]
      hostname: polt-simulator9
      environment:
        - PASSWD=root
        - POLT_SIMULATOR_REST_API_PORT=3010
      ports:
        - "10838:10830"
        - "3010:3010"
      #volumes:
        #- ./cli_scripts_new:/certificates/cli_scripts_new
      networks:
        obcas_e2e:
          ipv4_address: 172.47.0.14

    polt-simulator10:
      image: broadbandforum/obbaa-polt-simulator:develop
      stdin_open: true
      tty: true
      container_name: polt-simulator10
      #command: ["-dummy_tr385","-f","/certificates/cli_scripts_new/read_certs_start_server_new.cli"]
      command: ["-dummy_tr385"]
      hostname: polt-simulator10
      environment:
        - PASSWD=root
        - POLT_SIMULATOR_REST_API_PORT=3011
      ports:
        - "10839:10830"
        - "3011:3011"
      #volumes:
       # - ./cli_scripts_new:/certificates/cli_scripts_new
      networks:
        obcas_e2e:
          ipv4_address: 172.47.0.15


    onu-simulator1:
      image: broadbandforum/obbaa-onu-simulator:develop
      container_name: onu-simulator1
      stdin_open: true
      tty: true
      entrypoint: python3
      command: ["/usr/local/bin/onusim.py", "-p", "50000","-n","CT_1","-i", "1", "-I", "10", "-l", "2" ]
      hostname: onu-simulator1
      environment:
        - PASSWD=root
        - http_port=3018
      ports:
        - "50000:50000"
        - "3018:3018"
      networks:
        obcas_e2e:
          ipv4_address: 172.47.0.16

    onu-simulator2:
      image: broadbandforum/obbaa-onu-simulator:develop
      container_name: onu-simulator2
      stdin_open: true
      tty: true
      entrypoint: python3
      command: ["/usr/local/bin/onusim.py", "-p", "50001","-n","CT_1","-i", "1", "-I", "10", "-l", "2" ]
      hostname: onu-simulator2
      environment:
        - PASSWD=root
        - http_port=3019
      ports:
        - "50001:50001"
        - "3019:3019"
      networks:
        obcas_e2e:
          ipv4_address: 172.47.0.17

    onu-simulator3:
      image: broadbandforum/obbaa-onu-simulator:develop
      container_name: onu-simulator3
      stdin_open: true
      tty: true
      entrypoint: python3
      command: ["/usr/local/bin/onusim.py", "-p", "50002","-n","CT_1","-i", "1", "-I", "10", "-l", "2" ]
      hostname: onu-simulator3
      environment:
        - PASSWD=root
        - http_port=3020
      ports:
        - "50002:50002"
        - "3020:3020"
      networks:
        obcas_e2e:
          ipv4_address: 172.47.0.18

    onu-simulator4:
      image: broadbandforum/obbaa-onu-simulator:develop
      container_name: onu-simulator4
      stdin_open: true
      tty: true
      entrypoint: python3
      command: ["/usr/local/bin/onusim.py", "-p", "50003","-n","CT_1","-i", "1", "-I", "10", "-l", "2" ]
      hostname: onu-simulator4
      environment:
        - PASSWD=root
        - http_port=3021
      ports:
        - "50003:50003"
        - "3021:3021"
      networks:
        obcas_e2e:
          ipv4_address: 172.47.0.19

    onu-simulator5:
      image: broadbandforum/obbaa-onu-simulator:develop
      container_name: onu-simulator5
      stdin_open: true
      tty: true
      entrypoint: python3
      command: ["/usr/local/bin/onusim.py", "-p", "50004","-n","CT_1","-i", "1", "-I", "10", "-l", "2" ]
      hostname: onu-simulator5
      environment:
        - PASSWD=root
        - http_port=3022
      ports:
        - "50004:50004"
        - "3022:3022"
      networks:
        obcas_e2e:
          ipv4_address: 172.47.0.20

    onu-simulator6:
      image: broadbandforum/obbaa-onu-simulator:develop
      container_name: onu-simulator6
      stdin_open: true
      tty: true
      entrypoint: python3
      command: ["/usr/local/bin/onusim.py", "-p", "50005","-n","CT_1","-i", "1", "-I", "10", "-l", "2" ]
      hostname: onu-simulator6
      environment:
        - PASSWD=root
        - http_port=3023
      ports:
        - "50005:50005"
        - "3023:3023"
      networks:
        obcas_e2e:
          ipv4_address: 172.47.0.21

    onu-simulator7:
      image: broadbandforum/obbaa-onu-simulator:develop
      container_name: onu-simulator7
      stdin_open: true
      tty: true
      entrypoint: python3
      command: ["/usr/local/bin/onusim.py", "-p", "50006","-n","CT_1","-i", "1", "-I", "10", "-l", "2" ]
      hostname: onu-simulator7
      environment:
        - PASSWD=root
        - http_port=3024
      ports:
        - "50006:50006"
        - "3024:3024"
      networks:
        obcas_e2e:
          ipv4_address: 172.47.0.22

    onu-simulator8:
      image: broadbandforum/obbaa-onu-simulator:develop
      container_name: onu-simulator8
      stdin_open: true
      tty: true
      entrypoint: python3
      command: ["/usr/local/bin/onusim.py", "-p", "50007","-n","CT_1","-i", "1", "-I", "10", "-l", "2" ]
      hostname: onu-simulator8
      environment:
        - PASSWD=root
        - http_port=3025
      ports:
        - "50007:50007"
        - "3025:3025"
      networks:
        obcas_e2e:
          ipv4_address: 172.47.0.23

    onu-simulator9:
      image: broadbandforum/obbaa-onu-simulator:develop
      container_name: onu-simulator9
      stdin_open: true
      tty: true
      entrypoint: python3
      command: ["/usr/local/bin/onusim.py", "-p", "50008","-n","CT_1","-i", "1", "-I", "10", "-l", "2" ]
      hostname: onu-simulator9
      environment:
        - PASSWD=root
        - http_port=3026
      ports:
        - "50008:50008"
        - "3026:3026"
      networks:
        obcas_e2e:
          ipv4_address: 172.47.0.24

    onu-simulator10:
      image: broadbandforum/obbaa-onu-simulator:develop
      container_name: onu-simulator10
      stdin_open: true
      tty: true
      entrypoint: python3
      command: ["/usr/local/bin/onusim.py", "-p", "50009","-n","CT_1","-i", "1", "-I", "10", "-l", "2" ]
      hostname: onu-simulator10
      environment:
        - PASSWD=root
        - http_port=3027
      ports:
        - "50009:50009"
        - "3027:3027"
      networks:
        obcas_e2e:
          ipv4_address: 172.47.0.25

    baa:
      image: broadbandforum/baa:develop
      container_name: baa
      restart: always
      ports:
        - "8080:8080"
        - "5005:5005"
        - "9292:9292"
        - "4335:4335"
        - "162:162/udp"
      environment:
        - BAA_USER=admin
        - BAA_USER_PASSWORD=password
        #Possible Values for PMA_SESSION_FACTORY_TYPE are REGULAR,TRANSPARENT, Default value is REGULAR
        - PMA_SESSION_FACTORY_TYPE=REGULAR
        - MAXIMUM_ALLOWED_ADAPTER_VERSIONS=3
        - VOLTMF_NAME=vOLTMF
        # Enable Model Abstracter or Disable Model Abstracter, Default value is Disable
        - MODEL_ABSTRACTER_STATUS=Disable
        # Below tag shall be set as false if the BAA is going to be tested for Scalability/Performance
        - NC_ENABLE_POST_EDIT_DS_VALIDATION_SUPPORT=True
      volumes:
        - /baa/stores:/baa/stores
      networks:
        obcas_e2e:
          ipv4_address: 172.47.0.26
      tty: true
      stdin_open: true
      depends_on:
        - kafka
        - zookeeper

    opensearch-node1:
      image: opensearchproject/opensearch:2.14.0
      container_name: opensearch-node1
      environment:
        - cluster.name=opensearch-cluster
        - node.name=opensearch-node1
        - discovery.type=single-node
        #- discovery.seed_hosts=opensearch-node1,opensearch-node2
        #- cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2
        - bootstrap.memory_lock=true  # along with the memlock settings below, disables swapping
        - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m  # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
        - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Obcas@2024    # Sets the demo admin user password when using demo configuration, required for OpenSearch 2.12 and higher
      ulimits:
        memlock:
          soft: -1
          hard: -1
        nofile:
          soft: 65536  # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
          hard: 65536
      volumes:
        - opensearch-data1:/usr/share/opensearch/data
      ports:
        - 9200:9200
        - 9600:9600  #required for Performance Analyzer
      networks:
        obcas_e2e:
          ipv4_address: 172.47.0.27

    opensearch-dashboards:
      image: opensearchproject/opensearch-dashboards:2.14.0
      container_name: opensearch-dashboards
      ports:
        - 5601:5601
      expose:
        - '5601'
      environment:
        OPENSEARCH_HOSTS: '["https://opensearch-node1:9200"]'
      networks:
        obcas_e2e:
          ipv4_address: 172.47.0.28

    fluentd:
      image: broadbandforum/obcas-fluentd:v1.17-1
      container_name: fluentd
      environment:
        OS_IP: "172.47.0.27" #change the IP to public IP address of opensearch node
        OS_PORT: 9200
        OS_USER: "admin"
        OS_PASSWORD: "Obcas@2024"
        OS_PROTO: "https"
        LOG_INDEX_PATTERN: "logstash"
      links:
        - "opensearch-node1"
      ports:
        - "24224:24224"
        - "24224:24224/udp"
      networks:
        obcas_e2e:
          ipv4_address: 172.47.0.29
      depends_on:
        - opensearch-node1
        - opensearch-dashboards

volumes:
  opensearch-data1: